object Versions {
    const val accompanist = "0.25.1"
    const val activity = "1.5.1"
    const val appCompat = "1.5.1"
    const val composeLifecycle = "2.5.1"
    const val compose = "1.3.0-beta03"
    const val composeCompiler = "1.3.1"
    const val constraintLayout = "2.1.4"
    const val gradlePlugin = "4.2.1"
    const val jUnit = "4.13.2"
    const val koin = "3.2.0"
    const val kotlin = "1.7.10"
    const val ktor = "1.6.4"
    const val ktorVersion = "2.0.2"
    const val ktxCoroutine = "1.6.4"
    const val materialDesign = "1.6.1"
    const val navCompose = "2.5.2"
    const val timber = "5.0.1"
    const val richText = "0.13.0"
    const val kotest = "5.4.2"
}